### ISSUE TITLE
Just to check, your IJBA verification test, you just take the average of all features of each template, right?

### ISSUE THREAD

**Issue by yxchng** [AruniRC/resnet-face-pytorch#2]

**Comment by AruniRC** [comment]
Yes, it is simple average pooling, but followed by two other operations: L2-normalization, and optionally elementwise signed-square-root.
The code and descriptive comments are here: 
https://github.com/AruniRC/resnet-face-pytorch/blob/master/ijba/eval_ijba_1_1.py#L239
