### ISSUE TITLE
When testing on IJBA dataset, do you crop out the face first using FACE_X, FACE_Y, FACE_WIDTH, FACE_HEIGHT information?

### ISSUE THREAD

**Issue by yxchng** [AruniRC/resnet-face-pytorch#3]
Your code doesn't seem to have a part that uses these information. Do you pass the original image to your network? Many of the photos contain more than one faces.

**Comment by AruniRC** [comment]
We crop out the faces first using the information. It was done separately and the crops saved with SIGHTING_ID as separate files.
The current code just reads in these files.

**Comment by yxchng** [comment]
ok thanks
